### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tooconfident** [judithhinlung/prj-rev-bwfs-dasmoto#4]
Grade: Needs Improvement

Your code overall is looking really good here. You have a couple unfortunate typos in your css that set your project back and make your webpage visual design fall a little short. Once those typos are fixed though your code looks great. Your css is very clear and DRY (Don't Repeat Yourself). You make a solid choice using div containers and assigning class names to your spans. Another thing to consider is making your div containers have id names instead of class names since they are unique given your structure, or you can instead make each div have the same class name and assign id's to the `<h2>` elements in each section allowing you to make your css even more clean eliminating the need for repeating h2 child element selectors. Examples in the gist below:

https://gist.github.com/Tooconfident/21095a045d4a3828eb1c860200589917
https://gist.github.com/Tooconfident/b0b123bbe139f69202b1b9e4e38dd17d

**Comment by judithhinlung** [comment]
Thank you so much for the wonderful suggestions, I have incorporated all of them to make my code cleaner :)
